import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Sidebar from "@/components/Sidebar";
import "./globals.css";
import { MealPlanContextProvider } from "@/components/store/MealPlanContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <MealPlanContextProvider>
          <Sidebar />
          <main className="w-full h-full bg-[#222f3d] border-2 border-[#BFA181] rounded-lg p-4 overflow-y-hidden">
            {children}
          </main>
        </MealPlanContextProvider>
      </body>
    </html>
  );
}
