BEGIN
  FOR c IN (SELECT table_name FROM user_tables) LOOP
    EXECUTE IMMEDIATE ('DROP TABLE "' || c.table_name || '" CASCADE CONSTRAINTS');
  END LOOP;
END;
/




-- Generated by Oracle SQL Developer Data Modeler 23.1.0.087.0806
--   at:        2024-04-17 21:22:01 CEST
--   site:      Oracle Database 11g
--   type:      Oracle Database 11g



-- predefined type, no DDL - MDSYS.SDO_GEOMETRY

-- predefined type, no DDL - XMLTYPE

CREATE TABLE activity (
    activity_id       NUMBER(3) NOT NULL,
    name              VARCHAR2(30 CHAR) NOT NULL,
    calories_per_hour NUMBER(4) NOT NULL
);

ALTER TABLE activity ADD CONSTRAINT positive_calories_per_hour CHECK ( calories_per_hour > 0 );

ALTER TABLE activity ADD CONSTRAINT activity_pk PRIMARY KEY ( activity_id );

ALTER TABLE activity ADD CONSTRAINT activity_unique_name UNIQUE ( name );

CREATE TABLE activity_entry (
    activity_entry_id    NUMBER(9) NOT NULL,
    duration             NUMBER(6) NOT NULL,
    calories_burned      NUMBER(4),
    user_user_id         NUMBER(7) NOT NULL,
    activity_activity_id NUMBER(3) NOT NULL
);

COMMENT ON COLUMN activity_entry.duration IS
    'in seconds';

ALTER TABLE activity_entry ADD CONSTRAINT positive_duration CHECK ( duration > 0 );

ALTER TABLE activity_entry ADD CONSTRAINT positive_calories_burned CHECK ( calories_burned > 0 );

ALTER TABLE activity_entry
    ADD CONSTRAINT activity_entry_pk PRIMARY KEY ( activity_entry_id,
                                                   activity_activity_id,
                                                   user_user_id );

CREATE TABLE body_measurement_entry (
    body_measurement_entry_id NUMBER(9) NOT NULL,
    weight                    NUMBER(4, 1) NOT NULL,
    "date"                    DATE NOT NULL,
    user_user_id              NUMBER(7) NOT NULL
);

ALTER TABLE body_measurement_entry ADD CONSTRAINT positive_weight CHECK ( weight > 0 );

ALTER TABLE body_measurement_entry ADD CONSTRAINT body_measurement_entry_pk PRIMARY KEY ( body_measurement_entry_id,
                                                                                          user_user_id );

ALTER TABLE body_measurement_entry ADD CONSTRAINT unique_date UNIQUE ( "date" );

CREATE TABLE food (
    food_id                NUMBER(6) NOT NULL,
    name                   VARCHAR2(40 CHAR) NOT NULL,
    calories_per_100g      NUMBER(4, 1),
    proteins_per_100g      NUMBER(4, 1),
    fats_per_100g          NUMBER(4, 1),
    carbohydrates_per_100g NUMBER(4, 1),
    serving                NUMBER(4, 1),
    water                  NUMBER(4)
);

COMMENT ON COLUMN food.serving IS
    'in grams';

ALTER TABLE food ADD CONSTRAINT non_negative_calories CHECK ( calories_per_100g >= 0 );

ALTER TABLE food ADD CONSTRAINT non_negative_proteins CHECK ( proteins_per_100g >= 0 );

ALTER TABLE food ADD CONSTRAINT non_negative_fats CHECK ( fats_per_100g >= 0 );

ALTER TABLE food ADD CONSTRAINT non_negative_carbohydrates CHECK ( carbohydrates_per_100g >= 0 );

ALTER TABLE food ADD CONSTRAINT positive_serving CHECK ( serving > 0 );

ALTER TABLE food ADD CONSTRAINT non_negative_water CHECK ( water >= 0 );

ALTER TABLE food ADD CONSTRAINT food_pk PRIMARY KEY ( food_id );

ALTER TABLE food ADD CONSTRAINT food_unique_name UNIQUE ( name );

CREATE TABLE goal (
    goal_id                NUMBER(8) NOT NULL,
    goal_type              NUMBER NOT NULL,
    target_weigth          NUMBER(4, 1),
    start_date             DATE,
    end_date               DATE,
    user_user_id           NUMBER(7) NOT NULL,
    goal_type_goal_type_id NUMBER(3) NOT NULL
);

ALTER TABLE goal ADD CONSTRAINT positive_target_weigth CHECK ( target_weigth > 0 );

ALTER TABLE goal ADD CONSTRAINT goal_pk PRIMARY KEY ( goal_id,
                                                      user_user_id );

CREATE TABLE goal_type (
    goal_type_id NUMBER(3) NOT NULL,
    name         VARCHAR2(20 CHAR) NOT NULL
);

ALTER TABLE goal_type ADD CONSTRAINT goal_type_pk PRIMARY KEY ( goal_type_id );

ALTER TABLE goal_type ADD CONSTRAINT goal_type_unique_name UNIQUE ( name );

CREATE TABLE meal (
    meal_id                NUMBER(6) NOT NULL,
    water_consumption      NUMBER(4),
    calories               NUMBER(5, 1),
    proteins               NUMBER(4, 1),
    fats                   NUMBER(4, 1),
    carbohydrates          NUMBER(4, 1),
    meal_type_meal_type_id NUMBER(2) NOT NULL
);

COMMENT ON COLUMN meal.water_consumption IS
    'in ml';

ALTER TABLE meal ADD CONSTRAINT non_negative_water_consumption CHECK ( water_consumption >= 0 );

ALTER TABLE meal ADD CONSTRAINT positive_kcal CHECK ( calories > 0 );

ALTER TABLE meal ADD CONSTRAINT non_negative_protein CHECK ( proteins >= 0 );

ALTER TABLE meal ADD CONSTRAINT non_negative_fats2 CHECK ( fats >= 0 );

ALTER TABLE meal ADD CONSTRAINT non_negative_carbohydrates2 CHECK ( carbohydrates >= 0 );

ALTER TABLE meal ADD CONSTRAINT meal_pk PRIMARY KEY ( meal_id );

CREATE TABLE meal_entry (
    meal_entry_id NUMBER(9) NOT NULL,
    user_user_id  NUMBER(7) NOT NULL,
    date_time     DATE NOT NULL,
    meal_meal_id  NUMBER(6) NOT NULL
);

ALTER TABLE meal_entry
    ADD CONSTRAINT meal_entry_pk PRIMARY KEY ( meal_entry_id,
                                               meal_meal_id,
                                               user_user_id );

ALTER TABLE meal_entry ADD CONSTRAINT meal_entry_unique_date UNIQUE ( date_time );

CREATE TABLE meal_food (
    quantity     NUMBER(4, 1) NOT NULL,
    meal_meal_id NUMBER(6) NOT NULL,
    food_food_id NUMBER(6) NOT NULL
);

COMMENT ON COLUMN meal_food.quantity IS
    'in grams';

ALTER TABLE meal_food ADD CONSTRAINT positive_quantity CHECK ( quantity > 0 );

ALTER TABLE meal_food ADD CONSTRAINT meal_food_pk PRIMARY KEY ( food_food_id,
                                                                meal_meal_id );

CREATE TABLE meal_type (
    meal_type_id NUMBER(2) NOT NULL,
    name         VARCHAR2(20 CHAR) NOT NULL
);

ALTER TABLE meal_type ADD CONSTRAINT meal_type_pk PRIMARY KEY ( meal_type_id );

ALTER TABLE meal_type ADD CONSTRAINT meal_type_unique_name UNIQUE ( name );

CREATE TABLE "User" (
    user_id       NUMBER(7) NOT NULL,
    name          VARCHAR2(20 CHAR) NOT NULL,
    surname       VARCHAR2(30 CHAR) NOT NULL,
    email         VARCHAR2(60 CHAR) NOT NULL,
    password      VARCHAR2(60 CHAR) NOT NULL,
    date_of_birth DATE,
    gender        CHAR(1 CHAR),
    height        NUMBER(4, 1)
);

COMMENT ON COLUMN "User".height IS
    'in cm';

ALTER TABLE "User"
    ADD CONSTRAINT gender_constraint CHECK ( gender IN ( 'K', 'M', 'U' ) );

ALTER TABLE "User" ADD CONSTRAINT positive_height CHECK ( height > 0 );

ALTER TABLE "User" ADD CONSTRAINT user_pk PRIMARY KEY ( user_id );

ALTER TABLE "User" ADD CONSTRAINT user_unique_email UNIQUE ( email );

ALTER TABLE activity_entry
    ADD CONSTRAINT activity_entry_activity_fk FOREIGN KEY ( activity_activity_id )
        REFERENCES activity ( activity_id );

ALTER TABLE activity_entry
    ADD CONSTRAINT activity_entry_user_fk FOREIGN KEY ( user_user_id )
        REFERENCES "User" ( user_id )
            ON DELETE CASCADE;

ALTER TABLE body_measurement_entry
    ADD CONSTRAINT body_measurement_entry_user_fk FOREIGN KEY ( user_user_id )
        REFERENCES "User" ( user_id )
            ON DELETE CASCADE;

ALTER TABLE goal
    ADD CONSTRAINT goal_goal_type_fk FOREIGN KEY ( goal_type_goal_type_id )
        REFERENCES goal_type ( goal_type_id );

ALTER TABLE goal
    ADD CONSTRAINT goal_user_fk FOREIGN KEY ( user_user_id )
        REFERENCES "User" ( user_id )
            ON DELETE CASCADE;

ALTER TABLE meal_entry
    ADD CONSTRAINT meal_entry_meal_fk FOREIGN KEY ( meal_meal_id )
        REFERENCES meal ( meal_id )
            ON DELETE CASCADE;

ALTER TABLE meal_entry
    ADD CONSTRAINT meal_entry_user_fk FOREIGN KEY ( user_user_id )
        REFERENCES "User" ( user_id )
            ON DELETE CASCADE;

ALTER TABLE meal_food
    ADD CONSTRAINT meal_food_food_fk FOREIGN KEY ( food_food_id )
        REFERENCES food ( food_id )
            ON DELETE CASCADE;

ALTER TABLE meal_food
    ADD CONSTRAINT meal_food_meal_fk FOREIGN KEY ( meal_meal_id )
        REFERENCES meal ( meal_id )
            ON DELETE CASCADE;

ALTER TABLE meal
    ADD CONSTRAINT meal_meal_type_fk FOREIGN KEY ( meal_type_meal_type_id )
        REFERENCES meal_type ( meal_type_id )
            ON DELETE CASCADE;



-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                            11
-- CREATE INDEX                             0
-- ALTER TABLE                             47
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE MATERIALIZED VIEW LOG             0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0
